inputs:
  url:
    description: ''
    required: true
  gitHubAccessToken:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: ${{ inputs.url }}
        device: all
        gitHubAccessToken: ${{ inputs.gitHubAccessToken }}
        prCommentEnabled: true
        prCommentSaveOld: true
