name: '[ Production ] Lighthouse'

on: 
  merge:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
  
      - name: Lighthouse
        uses: ./.github/actions/lighthouse
        with:
          url: ${{ secrets.PRODUCTION_URL }}
