name: '[ Development ] Page Seed Insight'

on: 
  push:
    branches:
      - development

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
  
      - name: Lighthouse
        uses: ./.github/actions/lighthouse
        with:
          url: ${{ secrets.DEVELOPMENT_URL }}